project_id = "ylynmzpikmkwwvmytfsg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.process-report-structure]
verify_jwt = true

[functions.fetch-latest-db-structure-docs]
verify_jwt = true

[functions.sync-docs-to-project]
verify_jwt = true

[functions.generate-codebase-documentation]
verify_jwt = true

[functions.historic-translation-migration]
verify_jwt = true

[functions.historic-translation-validation]
verify_jwt = true

[functions.historic-translation-monitoring]
verify_jwt = true

[functions.intelligent-translation-migration]
verify_jwt = true

[functions.bulk-translation-migration]
verify_jwt = true

[functions.detect-language]
verify_jwt = true

[functions.ai-translation]
verify_jwt = true

[functions.translate-accounts]
verify_jwt = true

[functions.upsert-ui-translations]
verify_jwt = true

[functions.sql-maintenance]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-db-documentation]
verify_jwt = true

[functions.retroactive-translation-generation]
verify_jwt = true

[db]
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[auth]
enabled = true
external_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://ylynmzpikmkwwvmytfsg.supabase.co"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.kakao]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""