
-- 1) Ensure user_account_id auto-increments (creates an implicit sequence)
ALTER TABLE public.user_accounts
  ALTER COLUMN user_account_id
  ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2) Ensure the trigger exists to populate public.user_accounts on signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_new_user();
