-- Add comprehensive UI translation keys for sidebar navigation and account section
INSERT INTO public.ui_translations (ui_key, language_code_target, translated_text, original_text, source_field_name, source) VALUES
-- Navigation groups
('MENU_DASHBOARD', 'de', 'Dashboard', 'Dashboard', 'text', 'manual'),
('MENU_DASHBOARD', 'en', 'Dashboard', 'Dashboard', 'text', 'manual'),
('MENU_FINANCIAL_REPORTS', 'de', 'Finanzberichte', 'Financial Reports', 'text', 'manual'),
('MENU_FINANCIAL_REPORTS', 'en', 'Financial Reports', 'Financial Reports', 'text', 'manual'),
('MENU_COA_TRANSLATOR', 'de', 'Kontenplan-Übersetzer', 'CoA Translator', 'text', 'manual'),
('MENU_COA_TRANSLATOR', 'en', 'CoA Translator', 'CoA Translator', 'text', 'manual'),
('MENU_COA_MAPPER', 'de', 'Kontenplan-Mapper', 'CoA Mapper', 'text', 'manual'),
('MENU_COA_MAPPER', 'en', 'CoA Mapper', 'CoA Mapper', 'text', 'manual'),
('MENU_TRIAL_BALANCE_IMPORT', 'de', 'Testbilanz-Import', 'Trial Balance Import', 'text', 'manual'),
('MENU_TRIAL_BALANCE_IMPORT', 'en', 'Trial Balance Import', 'Trial Balance Import', 'text', 'manual'),
('MENU_JOURNAL_IMPORT', 'de', 'Journal-Import', 'Journal Import', 'text', 'manual'),
('MENU_JOURNAL_IMPORT', 'en', 'Journal Import', 'Journal Import', 'text', 'manual'),
('MENU_REPORT_STRUCTURES', 'de', 'Berichtstrukturen', 'Report Structures', 'text', 'manual'),
('MENU_REPORT_STRUCTURES', 'en', 'Report Structures', 'Report Structures', 'text', 'manual'),
('MENU_ADMIN', 'de', 'Administration', 'Admin', 'text', 'manual'),
('MENU_ADMIN', 'en', 'Admin', 'Admin', 'text', 'manual'),
('MENU_SYSTEM_TOOLS', 'de', 'System-Tools', 'System Tools', 'text', 'manual'),
('MENU_SYSTEM_TOOLS', 'en', 'System Tools', 'System Tools', 'text', 'manual'),
('MENU_USER_MANAGEMENT', 'de', 'Benutzerverwaltung', 'User Management', 'text', 'manual'),
('MENU_USER_MANAGEMENT', 'en', 'User Management', 'User Management', 'text', 'manual'),
('MENU_ACTIVITY_LOG', 'de', 'Aktivitätsprotokoll', 'Activity Log', 'text', 'manual'),
('MENU_ACTIVITY_LOG', 'en', 'Activity Log', 'Activity Log', 'text', 'manual'),
('MENU_MULTILINGUAL_MANAGEMENT', 'de', 'Mehrsprachige Verwaltung', 'Multilingual Management', 'text', 'manual'),
('MENU_MULTILINGUAL_MANAGEMENT', 'en', 'Multilingual Management', 'Multilingual Management', 'text', 'manual'),
('MENU_ENTITY_MANAGEMENT', 'de', 'Entitätsverwaltung', 'Entity Management', 'text', 'manual'),
('MENU_ENTITY_MANAGEMENT', 'en', 'Entity Management', 'Entity Management', 'text', 'manual'),
('MENU_ROLES_PERMISSIONS', 'de', 'Rollen & Berechtigungen', 'Roles & Permissions', 'text', 'manual'),
('MENU_ROLES_PERMISSIONS', 'en', 'Roles & Permissions', 'Roles & Permissions', 'text', 'manual'),
('MENU_LOGOUT', 'de', 'Abmelden', 'Logout', 'text', 'manual'),
('MENU_LOGOUT', 'en', 'Logout', 'Logout', 'text', 'manual'),
-- Navigation group labels
('NAV_GROUP_CORE', 'de', 'Kern', 'Core', 'text', 'manual'),
('NAV_GROUP_CORE', 'en', 'Core', 'Core', 'text', 'manual'),
('NAV_GROUP_DATA_IMPORTS', 'de', 'Daten-Importe', 'Data Imports', 'text', 'manual'),
('NAV_GROUP_DATA_IMPORTS', 'en', 'Data Imports', 'Data Imports', 'text', 'manual'),
('NAV_GROUP_ADMINISTRATION', 'de', 'Administration', 'Administration', 'text', 'manual'),
('NAV_GROUP_ADMINISTRATION', 'en', 'Administration', 'Administration', 'text', 'manual');