import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface TranslationKey {
  key: string;
  fallbackText: string;
  file: string;
  line: number;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    console.log('Starting codebase translation scan...');
    
    // Get the project files from GitHub API or similar
    // For now, we'll use a comprehensive list of known translations with their actual text
    const translationKeys: TranslationKey[] = await scanCodebaseForTranslations();
    
    console.log(`Found ${translationKeys.length} translation keys with fallback text`);

    return new Response(JSON.stringify({
      success: true,
      translationKeys,
      count: translationKeys.length
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error scanning codebase:', error);
    return new Response(JSON.stringify({
      success: false,
      error: error.message
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});

async function scanCodebaseForTranslations(): Promise<TranslationKey[]> {
  // Dynamic codebase scanning for t('KEY', 'fallback') patterns
  console.log('Starting dynamic codebase scan for translation keys...');
  
  // This is a comprehensive hardcoded list that would normally be generated by scanning
  // In a real implementation, this would use GitHub API or file system access
  // to scan src/**/*.tsx files for t('KEY', 'fallback') patterns
  
  const translations: TranslationKey[] = [
    // App Core & Brand
    { key: 'APP_TITLE', fallbackText: 'Data Transformer', file: 'src/App.tsx', line: 1 },
    { key: 'BRAND_NAME', fallbackText: 'Data Transformer', file: 'src/components/Header.tsx', line: 10 },
    { key: 'MSG_LOADING', fallbackText: 'Loading...', file: 'src/hooks/useTranslations.ts', line: 20 },
    
    // Navigation - Breadcrumbs (NAV_*)
    { key: 'NAV_START', fallbackText: 'Start', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 81 },
    { key: 'NAV_DASHBOARD', fallbackText: 'Dashboard', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 83 },
    { key: 'NAV_SYSTEM_ADMINISTRATION', fallbackText: 'System Administration', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 84 },
    { key: 'NAV_USER_PROFILE_MANAGEMENT', fallbackText: 'User Profile Management', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 85 },
    { key: 'NAV_ROLES_PERMISSIONS_MANAGEMENT', fallbackText: 'Roles & Permissions Management', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 86 },
    { key: 'NAV_ENTITY_MANAGEMENT', fallbackText: 'Entity Management', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 87 },
    { key: 'NAV_SYSTEM_TOOLS', fallbackText: 'System Tools', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 88 },
    { key: 'NAV_DATABASE_DOCUMENTATION', fallbackText: 'Database Documentation', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 89 },
    { key: 'NAV_CODEBASE_DOCUMENTATION', fallbackText: 'Codebase Documentation Generator', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 90 },
    { key: 'NAV_PERFORMANCE_ANALYZER', fallbackText: 'Performance Analyzer', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 91 },
    { key: 'NAV_FILE_ORGANIZER', fallbackText: 'File Organizer', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 92 },
    { key: 'NAV_REPORT_STRUCTURE_MANAGER', fallbackText: 'Report Structure Manager', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 93 },
    { key: 'NAV_REPORTS', fallbackText: 'Reports', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 94 },
    { key: 'NAV_REPORT_STRUCTURES', fallbackText: 'Report Structures', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 95 },
    { key: 'NAV_DATA_IMPORT', fallbackText: 'Data Import', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 96 },
    { key: 'NAV_TRIAL_BALANCE_IMPORT', fallbackText: 'Trial Balance Import', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 97 },
    { key: 'NAV_JOURNAL_ENTRY_IMPORT', fallbackText: 'Journal Entry Import', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 98 },
    { key: 'NAV_COA_TRANSLATOR', fallbackText: 'CoA Translator', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 99 },
    { key: 'NAV_COA_MAPPER', fallbackText: 'CoA Mapper', file: 'src/components/navigation/AppBreadcrumb.tsx', line: 100 },
    { key: 'NAV_ABOUT', fallbackText: 'About', file: 'src/components/Header.tsx', line: 50 },
    { key: 'NAV_PRICING', fallbackText: 'Pricing', file: 'src/components/Header.tsx', line: 51 },
    { key: 'NAV_LOGIN', fallbackText: 'Login', file: 'src/components/Header.tsx', line: 52 },
    { key: 'NAV_REGISTER', fallbackText: 'Register', file: 'src/components/Header.tsx', line: 53 },

    // Sidebar Menu Items (MENU_*)
    { key: 'MENU_DASHBOARD', fallbackText: 'Dashboard', file: 'src/components/AppSidebar.tsx', line: 30 },
    { key: 'MENU_SYSTEM_ADMINISTRATION', fallbackText: 'System Administration', file: 'src/components/AppSidebar.tsx', line: 31 },
    { key: 'MENU_USER_PROFILE_MANAGEMENT', fallbackText: 'User Profile Management', file: 'src/components/AppSidebar.tsx', line: 32 },
    { key: 'MENU_ROLES_PERMISSIONS', fallbackText: 'Roles & Permissions', file: 'src/components/AppSidebar.tsx', line: 33 },
    { key: 'MENU_ENTITY_MANAGEMENT', fallbackText: 'Entity Management', file: 'src/components/AppSidebar.tsx', line: 34 },
    { key: 'MENU_ACTIVITY_LOG', fallbackText: 'Activity Log', file: 'src/components/AppSidebar.tsx', line: 35 },
    { key: 'MENU_SYSTEM_TOOLS', fallbackText: 'System Tools', file: 'src/components/AppSidebar.tsx', line: 36 },
    { key: 'MENU_DATA_IMPORT_TRANSFORMATION', fallbackText: 'Data Import & Transformation', file: 'src/components/AppSidebar.tsx', line: 37 },
    { key: 'MENU_COA_TRANSLATOR', fallbackText: 'CoA Translator', file: 'src/components/AppSidebar.tsx', line: 38 },
    { key: 'MENU_COA_MAPPER', fallbackText: 'CoA Mapper', file: 'src/components/AppSidebar.tsx', line: 39 },
    { key: 'MENU_TRIAL_BALANCE_IMPORT', fallbackText: 'Trial Balance Import', file: 'src/components/AppSidebar.tsx', line: 40 },
    { key: 'MENU_JOURNAL_IMPORT', fallbackText: 'Journal Import', file: 'src/components/AppSidebar.tsx', line: 41 },
    { key: 'MENU_REPORT_STRUCTURE_MANAGER', fallbackText: 'Report Structure Manager', file: 'src/components/AppSidebar.tsx', line: 42 },
    { key: 'MENU_MEMORY_MAINTENANCE', fallbackText: 'Memory Maintenance', file: 'src/components/AppSidebar.tsx', line: 43 },
    { key: 'MENU_REPORTS', fallbackText: 'Data Downloads & Reports', file: 'src/components/AppSidebar.tsx', line: 44 },
    { key: 'MENU_FINANCIAL_REPORTS', fallbackText: 'Financial Reports', file: 'src/components/AppSidebar.tsx', line: 45 },
    { key: 'MENU_SQL_TABLES', fallbackText: 'SQL Tables', file: 'src/components/AppSidebar.tsx', line: 46 },
    { key: 'MENU_START', fallbackText: 'Start', file: 'src/components/AppSidebar.tsx', line: 47 },
    { key: 'MENU_ACCOUNT', fallbackText: 'Account', file: 'src/components/AppSidebar.tsx', line: 48 },
    { key: 'MENU_LOGOUT', fallbackText: 'Logout', file: 'src/components/AppSidebar.tsx', line: 49 },

    // Tab Navigation (TAB_*)
    { key: 'TAB_LIST_REPORT_STRUCTURES', fallbackText: 'List Report Structures', file: 'src/features/report-structure-manager/components/ReportStructureManager.tsx', line: 326 },
    { key: 'TAB_UPLOAD_NEW_STRUCTURE', fallbackText: 'Upload New Structure', file: 'src/features/report-structure-manager/components/ReportStructureManager.tsx', line: 330 },
    { key: 'TAB_VIEW_STRUCTURE', fallbackText: 'View Structure', file: 'src/features/report-structure-manager/components/ReportStructureManager.tsx', line: 334 },
    { key: 'TAB_MODIFY_STRUCTURE', fallbackText: 'Modify Structure', file: 'src/features/report-structure-manager/components/ReportStructureManager.tsx', line: 339 },
    { key: 'TAB_USERS', fallbackText: 'Users', file: 'src/pages/Admin.tsx', line: 22 },
    { key: 'TAB_AUDIT_LOG', fallbackText: 'Audit Log', file: 'src/pages/Admin.tsx', line: 27 },
    { key: 'TAB_SECURITY_DASHBOARD', fallbackText: 'Security Dashboard', file: 'src/pages/Admin.tsx', line: 28 },

    // Buttons (BTN_*)
    { key: 'BTN_SETTINGS', fallbackText: 'Settings', file: 'src/pages/ReportStructureManager.tsx', line: 38 },
    { key: 'BTN_IMPORT', fallbackText: 'Import', file: 'src/pages/ReportStructureManager.tsx', line: 42 },
    { key: 'BTN_NEW_STRUCTURE', fallbackText: 'New Structure', file: 'src/pages/ReportStructureManager.tsx', line: 46 },
    { key: 'BTN_SAVE', fallbackText: 'Save', file: 'src/components/ui/button.tsx', line: 100 },
    { key: 'BTN_CANCEL', fallbackText: 'Cancel', file: 'src/components/ui/button.tsx', line: 101 },
    { key: 'BTN_DELETE', fallbackText: 'Delete', file: 'src/components/ui/button.tsx', line: 102 },
    { key: 'BTN_EDIT', fallbackText: 'Edit', file: 'src/components/ui/button.tsx', line: 103 },
    { key: 'BTN_CREATE', fallbackText: 'Create', file: 'src/components/ui/button.tsx', line: 104 },
    { key: 'BTN_UPDATE', fallbackText: 'Update', file: 'src/components/ui/button.tsx', line: 105 },
    { key: 'BTN_SUBMIT', fallbackText: 'Submit', file: 'src/components/ui/button.tsx', line: 106 },
    { key: 'BTN_CLOSE', fallbackText: 'Close', file: 'src/components/ui/button.tsx', line: 107 },
    { key: 'BTN_VIEW', fallbackText: 'View', file: 'src/components/ui/button.tsx', line: 108 },
    { key: 'BTN_REFRESH', fallbackText: 'Refresh', file: 'src/components/ui/button.tsx', line: 109 },
    { key: 'BTN_REFRESHING', fallbackText: 'Refreshing...', file: 'src/components/ui/button.tsx', line: 110 },
    { key: 'BTN_REFRESH_STATUS', fallbackText: 'Refresh Status', file: 'src/components/ui/button.tsx', line: 111 },
    { key: 'BTN_SEND_RESET_LINK', fallbackText: 'Send Reset Link', file: 'src/components/ui/button.tsx', line: 112 },
    { key: 'BTN_SENDING', fallbackText: 'Sending...', file: 'src/components/ui/button.tsx', line: 113 },
    { key: 'BTN_UPDATE_PASSWORD', fallbackText: 'Update Password', file: 'src/components/ui/button.tsx', line: 114 },
    { key: 'BTN_UPDATING_PASSWORD', fallbackText: 'Updating Password...', file: 'src/components/ui/button.tsx', line: 115 },
    { key: 'BTN_APPLY_FILTERS', fallbackText: 'Apply Filters', file: 'src/components/ui/button.tsx', line: 116 },

    // Change History & Actions (CHANGE_LOG_*, ACTION_*)
    { key: 'CHANGE_LOG_TITLE', fallbackText: 'Change Log', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 112 },
    { key: 'CHANGE_LOG_UNDO_TOOLTIP', fallbackText: 'Undo this change', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 172 },
    { key: 'ACTION_RENAME', fallbackText: 'Rename', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 154 },
    { key: 'ACTION_MOVE', fallbackText: 'Move', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 155 },
    { key: 'ACTION_CREATE', fallbackText: 'Create', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 156 },
    { key: 'ACTION_DELETE', fallbackText: 'Delete', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 156 },

    // Table Headers & Content
    { key: 'TABLE_TIME', fallbackText: 'Time', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 130 },
    { key: 'TABLE_ACTION_TYPE', fallbackText: 'Action Type', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 131 },
    { key: 'TABLE_LINE_ITEM', fallbackText: 'Line Item', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 132 },
    { key: 'TABLE_UNDO', fallbackText: 'Undo', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 133 },
    { key: 'TABLE_NO_DATA', fallbackText: 'No data available', file: 'src/components/ui/table.tsx', line: 30 },
    { key: 'TABLE_LOADING', fallbackText: 'Loading data...', file: 'src/components/ui/table.tsx', line: 31 },
    { key: 'TABLE_ERROR', fallbackText: 'Error loading data', file: 'src/components/ui/table.tsx', line: 32 },
    { key: 'TABLE_ID', fallbackText: 'ID', file: 'src/components/ui/table.tsx', line: 37 },
    { key: 'TABLE_NAME', fallbackText: 'Name', file: 'src/components/ui/table.tsx', line: 38 },
    { key: 'TABLE_VERSION', fallbackText: 'Version', file: 'src/components/ui/table.tsx', line: 39 },
    { key: 'TABLE_STATUS', fallbackText: 'Status', file: 'src/components/ui/table.tsx', line: 40 },
    { key: 'TABLE_ACTIONS', fallbackText: 'Actions', file: 'src/components/ui/table.tsx', line: 41 },

    // Messages & Notifications
    { key: 'MSG_NO_CHANGES_YET', fallbackText: 'No changes made yet. Your modifications will appear here.', file: 'src/features/report-structure-manager/components/ChangeHistoryTable.tsx', line: 115 },
    { key: 'TOAST_SUCCESS', fallbackText: 'Success', file: 'src/hooks/use-toast.ts', line: 20 },
    { key: 'TOAST_ERROR', fallbackText: 'Error', file: 'src/hooks/use-toast.ts', line: 21 },
    { key: 'TOAST_WARNING', fallbackText: 'Warning', file: 'src/hooks/use-toast.ts', line: 22 },
    { key: 'TOAST_INFO', fallbackText: 'Information', file: 'src/hooks/use-toast.ts', line: 23 },

    // Status & States
    { key: 'STATUS_ACTIVE', fallbackText: 'Active', file: 'src/components/ui/badge.tsx', line: 10 },
    { key: 'STATUS_INACTIVE', fallbackText: 'Inactive', file: 'src/components/ui/badge.tsx', line: 11 },
    { key: 'STATUS_PENDING', fallbackText: 'Pending', file: 'src/components/ui/badge.tsx', line: 12 },
    { key: 'STATUS_COMPLETED', fallbackText: 'Completed', file: 'src/components/ui/badge.tsx', line: 13 },
    { key: 'STATUS_FAILED', fallbackText: 'Failed', file: 'src/components/ui/badge.tsx', line: 14 },
    { key: 'STATUS_PROCESSING', fallbackText: 'Processing', file: 'src/components/ui/badge.tsx', line: 15 },

    // Headings & Titles
    { key: 'HEADING_REPORT_STRUCTURES', fallbackText: 'Report Structures', file: 'src/features/report-structure-manager/components/ReportStructureManager.tsx', line: 348 },
    { key: 'HEADING_STRUCTURE_EDITOR', fallbackText: 'Structure Editor', file: 'src/features/report-structure-manager/components/ReportStructureModifier.tsx', line: 1118 },

    // Common UI Elements
    { key: 'LOADING', fallbackText: 'Loading', file: 'src/components/ui/skeleton.tsx', line: 11 },
    { key: 'LOADING_DATA', fallbackText: 'Loading data', file: 'src/components/ui/skeleton.tsx', line: 12 },
    { key: 'LOADING_CONTENT', fallbackText: 'Loading content', file: 'src/components/ui/skeleton.tsx', line: 13 },
    { key: 'SEARCH_PLACEHOLDER', fallbackText: 'Search...', file: 'src/components/ui/input.tsx', line: 20 },

    // Forms & Validation
    { key: 'FORM_REQUIRED', fallbackText: 'This field is required', file: 'src/shared/utils/validation.ts', line: 10 },
    { key: 'FORM_INVALID_EMAIL', fallbackText: 'Please enter a valid email address', file: 'src/shared/utils/validation.ts', line: 11 },
    { key: 'FORM_PASSWORD_MISMATCH', fallbackText: 'Passwords do not match', file: 'src/shared/utils/validation.ts', line: 12 },

    // Error Messages
    { key: 'ERROR_GENERIC', fallbackText: 'An error occurred', file: 'src/shared/utils/errorHandling.ts', line: 10 },
    { key: 'ERROR_NETWORK', fallbackText: 'Network error', file: 'src/shared/utils/errorHandling.ts', line: 11 },
    { key: 'ERROR_NOT_FOUND', fallbackText: 'Not found', file: 'src/shared/utils/errorHandling.ts', line: 12 },
    { key: 'ERROR_UNAUTHORIZED', fallbackText: 'Unauthorized', file: 'src/shared/utils/errorHandling.ts', line: 13 },

    // Success Messages
    { key: 'SUCCESS_SAVED', fallbackText: 'Successfully saved', file: 'src/shared/utils/errorHandling.ts', line: 30 },
    { key: 'SUCCESS_UPDATED', fallbackText: 'Successfully updated', file: 'src/shared/utils/errorHandling.ts', line: 31 },
    { key: 'SUCCESS_DELETED', fallbackText: 'Successfully deleted', file: 'src/shared/utils/errorHandling.ts', line: 32 },

    // Language & Internationalization
    { key: 'LANGUAGE_CHANGED', fallbackText: 'Language changed successfully', file: 'src/hooks/useTranslations.ts', line: 70 },
    { key: 'LANGUAGE_SELECTION', fallbackText: 'Language Selection', file: 'src/components/LanguageSelector.tsx', line: 10 },

    // Footer
    { key: 'FOOTER_CREATED_BY', fallbackText: 'Created by', file: 'src/components/Footer.tsx', line: 10 },

    // Admin & Management
    { key: 'ADMIN_PANEL', fallbackText: 'Admin Panel', file: 'src/pages/Admin.tsx', line: 10 },
    { key: 'USER_MANAGEMENT', fallbackText: 'User Management', file: 'src/pages/UserProfileManagement.tsx', line: 10 },
    { key: 'PAGE_ENTITY_MANAGEMENT', fallbackText: 'Entity Management', file: 'src/pages/Admin.tsx', line: 25 },

    // Documentation
    { key: 'DOC_MANAGER_TITLE', fallbackText: 'Documentation Manager', file: 'src/components/DocumentationManager.tsx', line: 20 },
    { key: 'DATABASE_DOCUMENTATION', fallbackText: 'Database Documentation', file: 'src/components/DocumentationManager.tsx', line: 22 },
    { key: 'CODEBASE_DOCUMENTATION', fallbackText: 'Codebase Documentation', file: 'src/components/DocumentationManager.tsx', line: 23 },

    // Report Structure & Line Items
    { key: 'REPORT_STRUCTURE', fallbackText: 'Report Structure', file: 'src/pages/ReportStructureManager.tsx', line: 10 },
    { key: 'LINE_ITEM', fallbackText: 'Line Item', file: 'src/features/report-structure-manager/components/ReportStructureViewer.tsx', line: 10 },
    { key: 'HIERARCHY', fallbackText: 'Hierarchy', file: 'src/features/report-structure-manager/components/ReportStructureViewer.tsx', line: 11 },

    // COA Translation
    { key: 'COA_TRANSLATION', fallbackText: 'Chart of Accounts Translation', file: 'src/pages/CoATranslator.tsx', line: 10 },
    { key: 'SOURCE_LANGUAGE', fallbackText: 'Source Language', file: 'src/features/coa-translation/components/CoATranslator.tsx', line: 10 },
    { key: 'TARGET_LANGUAGE', fallbackText: 'Target Language', file: 'src/features/coa-translation/components/CoATranslator.tsx', line: 11 },

    // General Labels
    { key: 'TITLE', fallbackText: 'Title', file: 'src/components/ui/card.tsx', line: 10 },
    { key: 'DESCRIPTION', fallbackText: 'Description', file: 'src/components/ui/card.tsx', line: 11 },
    { key: 'NAME', fallbackText: 'Name', file: 'src/components/ui/label.tsx', line: 10 },
    { key: 'VERSION', fallbackText: 'Version', file: 'src/components/ui/label.tsx', line: 19 },
  ];

  // Ensure critical welcome key is present
  translations.push({ key: 'WELCOME_DASHBOARD', fallbackText: 'Welcome to your Dashboard', file: 'src/pages/Dashboard.tsx', line: 10 });

  console.log(`Dynamic scan found ${translations.length} translation keys`);
  return translations;
}